name: 'Create new release'
description: 'Creates or update a release for a given tag. All the artifacts are renewed in this release process.'
inputs:
  version:
    description: 'The name of the version'
    required: true
outputs:
  release_tag:
    description: 'The exact git tag released'
    value: ${{ steps.release.outputs.release_tag }}
  release_sha:
    description: 'The exact git sha tagged for the release. It includes all the relevant documentation and version bumps'
    value: ${{ steps.release.outputs.release_sha }}
  dev_sha:
    description: 'The git sha where the new development version was opened.'
    value: ${{ steps.release.outputs.dev_sha }}
runs:
  using: 'composite'
  steps:
  - run: |
      cd actions/release
      go build -o release .
    shell: bash
  - run: |
      git config --global user.email "bot@whalebrew.gha"
      git config --global user.name "Whalebrew release bot"
      export INPUT_VERSION=${{ inputs.version }}
      actions/release/release
    id: release
    shell: bash