name: Close milestone and create release
on:
    milestone:
        types:
        - closed
jobs:
    update_version:
        name: Update version
        runs-on: ubuntu-latest

        steps:

        - name: Check out code into the Go module directory
          uses: actions/checkout@v2-beta
        
        - name: Create version
          run: |
            sed -i 's:const Version.*:const Version = "${{ github.event.milestone.title }}":' version/version.go
            (
                echo "# Change log"
                echo
                echo "## ${{ github.event.milestone.title }} - $(date +"%Y-%m-%d")" 
                echo "${{ github.event.milestone.description }}" | tr '\r\n' '\n'
                tail -n +2 CHANGELOG.md
            ) > CHANGELOG.md.new
            mv CHANGELOG.md.new CHANGELOG.md
        
        - name: Publish version
          run: |
            git add version/version.go CHANGELOG.md
            git config --global user.name "whalebrew-bot"
            git config --global user.email "whalebrew@users.noreply.github.com"
            git commit -m '[Auto] Bump version'
            git remote -vvv
            git config --global credential.helper store
            git push origin HEAD:refs/heads/master

        - name: Create Release
          id: create_release
          uses: actions/github-script@0.4.0
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                github.repos.createRelease({
                    owner: '${{ github.event.repository.owner.login }}',
                    repo: '${{ github.event.repository.name }}',
                    tag_name: '${{ github.event.milestone.title }}',
                    target_commitish: 'master',
                    name: '${{ github.event.milestone.title }}',
                    body: '${{ github.event.milestone.description }}',
                    draft: false,
                    prerelease: false
                })