name: Push & PR
on: 
  workflow_dispatch:
  # push:
  #   branches:
  #   - "**"
  #   tags:
  #   - "**"
  # pull_request:
  # merge_group:

jobs:

  build-test:
    name: Build and test ${{ github.event_name }}
    uses: ./.github/workflows/build-test.yaml
    with:
      git_ref: ${{ github.ref }}

  release:
    needs: build-test
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    uses: ./.github/workflows/publish-release-artifacts.yaml
    with:
      git_ref: ${{ github.ref }}
