name: Release

on:
  workflow_dispatch:
    input:
      version:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
        # fetch all tags
        fetch-depth: 0
    - name: "Bump in-tree versions"
      uses: ./actions/release-assets
      with:
        version: inputs.version
