name: Release
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true

jobs:
    build:
        uses: ./.github/workflows/go.yml
        with:
            tag: ${{ github.event.inputs.tag }}
    release:
        name: release
        runs-on: ubuntu-latest
        needs: build
        outputs:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
        
        - name: Check out code into the Go module directory
          uses: actions/checkout@v4
          with:
            # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
            # fetch all tags
            fetch-depth: 0
    
        - name: Download assets
          id: download
          uses: actions/download-artifact@v3
          with:
            path: release/artifacts

        - name: Create Release
          id: create_release
          uses: ./actions/release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            folder: ${{steps.download.outputs.download-path}}
            tag_name: ${{ github.event.inputs.tag }}   

        - name: Commit changelog
          run: |
            find "${{steps.download.outputs.download-path}}"
            cp "${{steps.download.outputs.download-path}}/CHANGELOG.md/CHANGELOG.md" CHANGELOG.md
            sed -i.old 's,https://github.com/whalebrew/whalebrew/releases/download/[^/]*/whalebrew,https://github.com/whalebrew/whalebrew/releases/download/{{ github.event.inputs.tag }}/whalebrew,' README.md
            rm README.md.old
            git config --local user.email "whalebrew@users.noreply.github.com"
            git config --local user.name "whalebrew release bot"
            git add CHANGELOG.md README.md
            git commit -m "Release ${{ github.event.inputs.tag }}"
            git remote -vvv
            git push origin HEAD:main
