name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.WHALEBREW_RELEASE_APP_ID }}
        private-key: ${{ secrets.WHALEBREW_RELEASE_SIGNING_KEY }}