name: Release

on:
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       type: string
  #       required: true
  push:
    branches:
    - automate-release

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.WHALEBREW_RELEASE_APP_ID }}
        private-key: ${{ secrets.WHALEBREW_RELEASE_SIGNING_KEY }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
        # fetch all tags
        fetch-depth: 0 
        token: ${{ steps.app-token.outputs.token }}
    - name: "Release tree"
      id: release-tree
      uses: ./actions/release
      with:
        version: 0.5.0-rc1
        step: create_release
    # - run: |
    #     echo "${{ toJSON(steps.release-tree.outputs) }}"
    #     git push origin \
    #       "${{ steps.release-tree.outputs.release_sha }}:refs/heads/auto/release/0.5.0-rc1"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ steps.app-token.outputs.token }}
        branch: "auto/release/0.5.0-rc1"
        delete-branch: true
        #base: master
        title: Create release 0.5.0-rc1
        labels: auto,release