name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

permissions:
  contents: write

jobs:
  create-release-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
        # fetch all tags
        fetch-depth: 0
    - name: "Release tree"
      id: release-tree
      uses: ./actions/release
      with:
        version: ${{ inputs.version }}
    - run: |
        echo "${{ toJSON(steps.release-tree.outputs) }}"
        git push origin \
          "${{ steps.release-tree.outputs.release_sha }}:refs/heads/release/${{ inputs.version }}" \
          "${{ steps.release-tree.outputs.dev_sha }}:refs/heads/dev/${{ steps.release-tree.outputs.dev_version }}"
  test:
    needs:
    - create-release-commits
    uses: ./.github/workflows/test.yaml
    with:
      git_ref: ${{ github.ref }}
