name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

permissions:
  contents: write

jobs:
  create-release-commits:
    runs-on: ubuntu-latest
    outputs:
      version_ref: "refs/heads/release/${{ inputs.version }}"
      dev_ref: "refs/heads/dev/${{ steps.release-tree.outputs.dev_version }}"
      tag: "${{ steps.release-tree.outputs.release_tag }}"
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
        # fetch all tags
        fetch-depth: 0
    - name: "Release tree"
      id: release-tree
      uses: ./actions/release
      with:
        version: ${{ inputs.version }}
    - run: |
        echo "${{ toJSON(steps.release-tree.outputs) }}"
        # Push all the built references but hide the tag until 
        git push origin \
          "${{ steps.release-tree.outputs.release_sha }}:refs/heads/release/${{ inputs.version }}" \
          "${{ steps.release-tree.outputs.dev_sha }}:refs/heads/dev/${{ steps.release-tree.outputs.dev_version }}" # \
          "${{ steps.release-tree.outputs.release_tag }}:refs/heads/next-tag/${{ steps.release-tree.outputs.release_tag }}"
  test-release:
    needs:
    - create-release-commits
    uses: ./.github/workflows/test.yaml
    with:
      git_ref: "${{ needs.create-release-commits.outputs.version_ref }}"
  test-next-dev:
    needs:
    - create-release-commits
    uses: ./.github/workflows/test.yaml
    with:
      git_ref: "${{ needs.create-release-commits.outputs.dev_ref }}"
  next-tag:
    needs:
    - create-release-commits
    uses: ./.github/workflows/test.yaml
    with:
      git_ref: "refs/heads/next-tag/${{ needs.create-release-commits.outputs.tag }}"
